//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ufiles.Email.UFilesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.GroupRestriction[] GroupRestrictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.GroupRestriction[] GroupRestrictions {
            get {
                return this.GroupRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupRestrictionsField, value) != true)) {
                    this.GroupRestrictionsField = value;
                    this.RaisePropertyChanged("GroupRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.FileAccessEvent[] FileAccessEventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.File[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Group[] MemberGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Group[] OwnedGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Transmittal[] ReceivedTransmittalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Transmittal[] SentTransmittalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.UserEvent[] UserEventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.UserRestriction[] UserRestrictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerifiedHashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.FileAccessEvent[] FileAccessEvents {
            get {
                return this.FileAccessEventsField;
            }
            set {
                if ((object.ReferenceEquals(this.FileAccessEventsField, value) != true)) {
                    this.FileAccessEventsField = value;
                    this.RaisePropertyChanged("FileAccessEvents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.File[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Group[] MemberGroups {
            get {
                return this.MemberGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberGroupsField, value) != true)) {
                    this.MemberGroupsField = value;
                    this.RaisePropertyChanged("MemberGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Group[] OwnedGroups {
            get {
                return this.OwnedGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnedGroupsField, value) != true)) {
                    this.OwnedGroupsField = value;
                    this.RaisePropertyChanged("OwnedGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Transmittal[] ReceivedTransmittals {
            get {
                return this.ReceivedTransmittalsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivedTransmittalsField, value) != true)) {
                    this.ReceivedTransmittalsField = value;
                    this.RaisePropertyChanged("ReceivedTransmittals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Transmittal[] SentTransmittals {
            get {
                return this.SentTransmittalsField;
            }
            set {
                if ((object.ReferenceEquals(this.SentTransmittalsField, value) != true)) {
                    this.SentTransmittalsField = value;
                    this.RaisePropertyChanged("SentTransmittals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.UserEvent[] UserEvents {
            get {
                return this.UserEventsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEventsField, value) != true)) {
                    this.UserEventsField = value;
                    this.RaisePropertyChanged("UserEvents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.UserRestriction[] UserRestrictions {
            get {
                return this.UserRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRestrictionsField, value) != true)) {
                    this.UserRestrictionsField = value;
                    this.RaisePropertyChanged("UserRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Verified {
            get {
                return this.VerifiedField;
            }
            set {
                if ((this.VerifiedField.Equals(value) != true)) {
                    this.VerifiedField = value;
                    this.RaisePropertyChanged("Verified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerifiedHash {
            get {
                return this.VerifiedHashField;
            }
            set {
                if ((object.ReferenceEquals(this.VerifiedHashField, value) != true)) {
                    this.VerifiedHashField = value;
                    this.RaisePropertyChanged("VerifiedHash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupRestriction", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class GroupRestriction : Ufiles.Email.UFilesService.Restriction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Group[] GroupsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Group[] Groups {
            get {
                return this.GroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupsField, value) != true)) {
                    this.GroupsField = value;
                    this.RaisePropertyChanged("Groups");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restriction", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ufiles.Email.UFilesService.UserRestriction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ufiles.Email.UFilesService.GroupRestriction))]
    public partial class Restriction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RestrictionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RestrictionId {
            get {
                return this.RestrictionIdField;
            }
            set {
                if ((this.RestrictionIdField.Equals(value) != true)) {
                    this.RestrictionIdField = value;
                    this.RaisePropertyChanged("RestrictionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRestriction", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class UserRestriction : Ufiles.Email.UFilesService.Restriction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User[] UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileAccessEvent", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class FileAccessEvent : Ufiles.Email.UFilesService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.File FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.File File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class File : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.FileAccessEvent[] FileAccessEventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Restriction[] RestrictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RevokedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Transmittal[] TransmittalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.FileAccessEvent[] FileAccessEvents {
            get {
                return this.FileAccessEventsField;
            }
            set {
                if ((object.ReferenceEquals(this.FileAccessEventsField, value) != true)) {
                    this.FileAccessEventsField = value;
                    this.RaisePropertyChanged("FileAccessEvents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileId {
            get {
                return this.FileIdField;
            }
            set {
                if ((this.FileIdField.Equals(value) != true)) {
                    this.FileIdField = value;
                    this.RaisePropertyChanged("FileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Restriction[] Restrictions {
            get {
                return this.RestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.RestrictionsField, value) != true)) {
                    this.RestrictionsField = value;
                    this.RaisePropertyChanged("Restrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Revoked {
            get {
                return this.RevokedField;
            }
            set {
                if ((this.RevokedField.Equals(value) != true)) {
                    this.RevokedField = value;
                    this.RaisePropertyChanged("Revoked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Transmittal[] Transmittals {
            get {
                return this.TransmittalsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmittalsField, value) != true)) {
                    this.TransmittalsField = value;
                    this.RaisePropertyChanged("Transmittals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transmittal", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class Transmittal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.File[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User[] RecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.TransmittalEvent[] TransmittalEventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransmittalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.File[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User[] Recipients {
            get {
                return this.RecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsField, value) != true)) {
                    this.RecipientsField = value;
                    this.RaisePropertyChanged("Recipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sent {
            get {
                return this.SentField;
            }
            set {
                if ((this.SentField.Equals(value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.TransmittalEvent[] TransmittalEvents {
            get {
                return this.TransmittalEventsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmittalEventsField, value) != true)) {
                    this.TransmittalEventsField = value;
                    this.RaisePropertyChanged("TransmittalEvents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransmittalId {
            get {
                return this.TransmittalIdField;
            }
            set {
                if ((this.TransmittalIdField.Equals(value) != true)) {
                    this.TransmittalIdField = value;
                    this.RaisePropertyChanged("TransmittalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserEvent", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class UserEvent : Ufiles.Email.UFilesService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ufiles.Email.UFilesService.TransmittalEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ufiles.Email.UFilesService.UserEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ufiles.Email.UFilesService.FileAccessEvent))]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OccurredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Occurred {
            get {
                return this.OccurredField;
            }
            set {
                if ((this.OccurredField.Equals(value) != true)) {
                    this.OccurredField = value;
                    this.RaisePropertyChanged("Occurred");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransmittalEvent", Namespace="http://schemas.datacontract.org/2004/07/UFiles.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class TransmittalEvent : Ufiles.Email.UFilesService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ufiles.Email.UFilesService.Transmittal TransmittalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ufiles.Email.UFilesService.Transmittal Transmittal {
            get {
                return this.TransmittalField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmittalField, value) != true)) {
                    this.TransmittalField = value;
                    this.RaisePropertyChanged("Transmittal");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UFilesService.IUFileService")]
    public interface IUFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUFileService/Login", ReplyAction="http://tempuri.org/IUFileService/LoginResponse")]
        int Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUFileService/GetGroups", ReplyAction="http://tempuri.org/IUFileService/GetGroupsResponse")]
        Ufiles.Email.UFilesService.Group[] GetGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUFileService/NewTransmittal", ReplyAction="http://tempuri.org/IUFileService/NewTransmittalResponse")]
        int NewTransmittal(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUFileService/AddFile", ReplyAction="http://tempuri.org/IUFileService/AddFileResponse")]
        void AddFile(int userId, int transmittalId, string fileName, string fileType, byte[] fileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUFileService/AddRecipients", ReplyAction="http://tempuri.org/IUFileService/AddRecipientsResponse")]
        void AddRecipients(int transmittalId, string[] recipients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUFileService/SendTransmittal", ReplyAction="http://tempuri.org/IUFileService/SendTransmittalResponse")]
        void SendTransmittal(int transmittalId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUFileServiceChannel : Ufiles.Email.UFilesService.IUFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UFileServiceClient : System.ServiceModel.ClientBase<Ufiles.Email.UFilesService.IUFileService>, Ufiles.Email.UFilesService.IUFileService {
        
        public UFileServiceClient() {
        }
        
        public UFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public Ufiles.Email.UFilesService.Group[] GetGroups() {
            return base.Channel.GetGroups();
        }
        
        public int NewTransmittal(int userId) {
            return base.Channel.NewTransmittal(userId);
        }
        
        public void AddFile(int userId, int transmittalId, string fileName, string fileType, byte[] fileData) {
            base.Channel.AddFile(userId, transmittalId, fileName, fileType, fileData);
        }
        
        public void AddRecipients(int transmittalId, string[] recipients) {
            base.Channel.AddRecipients(transmittalId, recipients);
        }
        
        public void SendTransmittal(int transmittalId) {
            base.Channel.SendTransmittal(transmittalId);
        }
    }
}
